FROM maven:3.6.3-jdk-11 as build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn -B package --file pom.xml

FROM openjdk:11-jre-slim
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app.jar"]
